version: '3.2'

volumes:
  node_modules:

services:
  php:
    image: yiisoftware/yii-php:7.3-apache
    working_dir: /app
    depends_on:
      - db
    volumes:
      - c:/FREP/DOCKER/weasy:/app
      # TODO: temporary workaround for public web-root
      - c:/FREP/DOCKER/weasy/public:/app/web
      # host-volume for composer cache
      - c:/FREP/DOCKER/weasy/~/.composer-docker/cache:/root/.composer/cache:delegated
      # fix node issue as of https://github.com/sass/node-sass/issues/2520
      - node_modules:/app/node_modules
    ports:
      - '8010:80'
  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./_host-volumes/runtime/mysql
        target: /app/runtime/mysql
        consistency: delegated