version: '3'

services:

  php:
    image: yiisoftware/yii-php:7.3-apache
    working_dir: /app
    volumes:
      - c:/FREP/DOCKER/weasy:/app
      # TODO: temporary workaround for public web-root
      - c:/FREP/DOCKER/weasy/web:/app/web
      # host-volume for composer cache
      - c:/FREP/DOCKER/weasy/~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8010:80'