version: '3'
services:
  php:
    image: yiisoftware/yii-php:7.3-apache
    volumes:
       - c:/FREP/DOCKER/weasy/weasy:/app
      # TODO: temporary workaround for public web-root
      - c:/FREP/DOCKER/weasy/weasy/public:/app/web
      # host-volume for composer cache
      - c:/FREP/DOCKER/weasy/weasy/~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8010:80'